const event = require('./models/events')
const mongoose = require('mongoose')
const eventArray = [
    
    {
        name: 'Bike Week',
        location: 'Goa',
        description: 'India Bike Week embodies this love in one insane weekend of revelry, racing and respect.A land where character is currency.And where every journey finds one hell of a destination.Welcome to the land of the wild.',
        website: 'https://indiabikeweek.in/',
        fb: 'https://www.facebook.com/indiabikeweek/',
        image: 'https://pbs.twimg.com/media/ED3Wd6nU8AEyPcK.jpg',
        type: 'Stunt',
        email: 'as77jadoun@gmail.com',
        mobile: '6232151111',
        footfall: '12000',
        target: 'Youth',
    },
    {
        name: 'Sparsh',
        location: 'SVNIT, Surat',
        description: 'Sparsh is the annual cultural festival of the SVNIT. It usually takes place in the second or third week of February, and is one of the largest of its kind in the Western Region. This festival consists of mega-attractions, informal events and numerous other competitions.',
        website: 'https://en.wikipedia.org/wiki/Sparsh_(festival)',
        fb: 'https://www.facebook.com/Sparsh.NITsurat/',
        image: 'https://cdn.thecollegefever.com/upload/27330162-1512297643632.jpg',
        type: 'Cultural',
        email: 'as77jadoun@gmail.com',
        mobile: '6232151111',
        footfall: '5000',
        target: 'Youth',
    },
    {
        name: "Rendezvous",
        location: "IIT Delhi",
        description: "Rendezvous, is the annual Cultural Festival of the Indian Institute of Technology (IIT), Delhi. It is a four-day-long event held in October every year. In the 2019 version, Rendezvous hosted 280+ events and had a footfall of over 163,000, 15,000+ participants and 200+ artists from more than 25 countries.",
        website: "",
        fb: "",
        image: 'https://scontent.fixc2-1.fna.fbcdn.net/v/t1.6435-9/70695062_2536585869714212_6162568455263354880_n.jpg?_nc_cat=108&ccb=1-3&_nc_sid=973b4a&_nc_ohc=f6wzUYxk_x0AX_8m_Ym&_nc_ht=scontent.fixc2-1.fna&oh=5d7e2029cdb7a067be292c3c8469367d&oe=60A3351B',
        type: "Cultural Festival",
        email: "as77jadoun@gmail.com",
        mobile: '6232151111',
        footfall: '12000',
        target: 'College Youth',
    },
    {
        name: 'Antaragini',
        location: 'IIT Kanpur',
        description: 'Antaragni is the annual cultural festival of IIT Kanpur and one of the biggest across Asia. With a legacy of 55 years, Antaragni entertains a footfall of over 130,000 to provide a highly competitive national level platform and host concerts of artists with international repute.',
        website: 'https://antaragni.in/',
        fb: 'https://www.facebook.com/antaragni.iitk/',
        image: 'https://pbs.twimg.com/profile_images/740937288385957888/sZtDPZPg.jpg',
        type: 'College Fest',
        email: 'as77jadoun@gmail.com',
        mobile: '6232151111',
        footfall: '9000',
        target: 'Youth',
    },
    {
        name: 'Confluence',
        location: 'Nit Kurukshetra',
        description: 'Confluence, popularly known as conflu, is the annual cultural festival of the National Institute of Technology Kurukshetra. It is a four-day long event held towards the end of February every year. It draws a footfall of more than 15,000 students from more than 60 colleges from across the country.',
        website: 'https://nitkkr.ac.in/sub_courses.php?id=107&id3=83',
        fb: 'https://www.facebook.com/Conflu/',
        image: 'https://miro.medium.com/max/1031/1*f0kYRnZXcGerDIFEru0tZg.png',
        type: 'College Fest',
        email: 'as77jadoun@gmail.com',
        mobile: '6232151111',
        footfall: '15000',
        target: 'Youth',
    },
    {
        name: 'Techniti',
        location: 'Nit Jalandhar',
        description: 'Started In 2006-TechNITi is an annual techno-managerial fest of NIT Jalandhar, an opportunity for students from all over the country from a diversity of fields to unite and celebrate our various identities, now conjoined, as one.',
        website: 'https://www.nitj.ac.in/index.php/nitj_cinfo/pages/275',
        fb: 'https://www.facebook.com/nitjtechniti/',
        image: 'https://scontent.fbho3-1.fna.fbcdn.net/v/t1.18169-9/12472484_592667160911407_576256556061897667_n.jpg?_nc_cat=109&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=m1h48Xnjdd0AX-yrmEU&_nc_ht=scontent.fbho3-1.fna&oh=0cf4ee214f373a303b7dad5c2c41316f&oe=60A2C4F1',
        type: 'College Fest',
        email: 'as77jadoun@gmail.com',
        mobile: '6232151111',
        footfall: '8000',
        target: 'Youth',
    },
    {
        name: 'Magnetic Fields',
        location: 'Shekhawati',
        description: 'Magnetic Fields Festival is a music festival held in Alsisar, Rajasthan, India over 3 days. A contemporary, future-facing, forward-thinking festival, it is India\'s premier boutique festival. Magnetic Fields is our community, it is a festival that absorbs and unites participants, crew, artists and guests.',
        website: 'https://www.magneticfields.in/',
        fb: 'https://www.facebook.com/magneticfieldsfestival/',
        image: 'https://nomads.magneticfields.in/images/social.jpg',
        type: 'Cultural',
        email: 'as77jadoun@gmail.com',
        mobile: '6232151111',
        footfall: '19000',
        target: 'All generations',
    },
    {
        name: "Sunburn",
        location: "Goa",
        description: "Sunburn, a Percept Intellectual Property, is Asia’s Premiere Electronic Dance Music (EDM) Festival, and is ranked amongst the world’s biggest music festivals. Sunburn has grown to become an aspirational lifestyle brand boasting an eclectic mix of music, entertainment and celebration.",
        website: "",
        fb: "",
        image: 'https://d31fr2pwly4c4s.cloudfront.net/a/8/0/1235411_0_sunburn-festival_400.jpg' ,
        type: "EDM Night",
        email: "as77jadoun@gmail.com",
        mobile: '6232151111',
        footfall: '61000',
        target: 'Youth',
    },
    {
        name: 'Himachal Hills',
        location: 'Kasol, Himachal Pradesh',
        description: 'It’s a two day extravaganza at a serene environment, under sky full of stars. There will be ROCK bands and live EDM’s who are experienced in pumping up the crowd and ensuring an unforgettable performance by playing your favorite genres.',
        website: 'https://timesofindia.indiatimes.com/travel/destinations/himachal-to-celebrate-himachal-hills-festival-from-december-30-31/as67205358.cms',
        fb: 'https://www.facebook.com/HimachalHillsFestival/',
        image: 'https://pbs.twimg.com/media/EMX5JViVAAETiNr.jpg',
        type: 'Fest',
        email: 'as77jadoun@gmail.com',
        mobile: '6232151111',
        footfall: '15000',
        target: 'Youth',
    },
    {
        name: "Dance Fest",
        location: "Pune",
        description: "Indian Dance Festival is the biggest of its kind in India. It brings together the best Indian dance troupes from all over the world and showcases the rich culture of Indian dance.xperience the grandeur of the Show Night and participate in the many interesting and colorful activities during the festival weekend!",
        website: "",
        fb: "",
        image: 'https://images.squarespace-cdn.com/content/v1/56bcaaf527d4bdc747db5d6d/1553266312638-04UZ78D8EYS4INAXL84C/ke17ZwdGBToddI8pDm48kFWxnDtCdRm2WA9rXcwtIYR7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UcTSrQkGwCGRqSxozz07hWZrYGYYH8sg4qn8Lpf9k1pYMHPsat2_S1jaQY3SwdyaXg/IDF_19+Website+Banner+Full+1500+x+1000+Limited.jpg?format=1500w' ,
        type: "Dance event",
        email: "as77jadoun@gmail.com",
        mobile: '6232151111',
        footfall: '20000',
        target: 'Youth, Dancers',
    },
    {
        name: "Tedx Pune",
        location: "Pune",
        description: "A TEDx event is a local gathering where live TED-like talks and performances are shared with the community. TEDx events are fully planned and coordinated independently, on a community-by-community basis. The content and design of each TEDx event is unique and developed independently, but all of them have features in common.",
        website: "https://www.ted.com/tedx/events/31567",
        fb: "https://www.facebook.com/TEDxPUNE/",
        image: 'https://media-exp1.licdn.com/dms/image/C4E1BAQF0gzKnz5_4xw/company-background_10000/0/1547007519701?e=2159024400&v=beta&t=fd284r5sDycVxydjR0XHAF4b5yDLSxENIBiwOHWgwPc' ,
        type: "Ted talk",
        email: "as77jadoun@gmail.com",
        mobile: '6232151111',
        footfall: '2000',
        target: 'Youth and working professional',
    },
    {
        name: "Adex Expo",
        location: "Mumbai",
        description: "Apex India has great pride in our global associations with Hospitality leaders in different technology sectors.Apex India has been the major contributor in Vingcard sales in India with continuous good performance and also was named the best global distributor among 166 countries in 2011 in shanghai.",
        website: "",
        fb: "",
        image: 'https://lh3.googleusercontent.com/proxy/GcY-9P4Bn-ELwjQ8KZjQ1izfisPLq7cz4wbZJsYwL3uTIoCEo92CG2ILJvKgfDSBOX-gXK9oXlMe5ERh6WX59HXhZiCu6YY7Y7mitYY_1A4' ,
        type: "Exports and sales",
        email: "as77jadoun@gmail.com",
        mobile: '6232151111',
        footfall: '7000',
        target: 'Professionals in sales and exports',
    }
]
mongoose.connect('mongodb://localhost:27017/spoonsify', { useNewUrlParser: true, useCreateIndex: true, useUnifiedTopology: true, useFindAndModify: false, })
const db = mongoose.connection;
db.on("error", console.error.bind(console, 'Connection error:'))
db.once("open", function () {
    console.log('Database Connected');
})

const addEvents = async function(){
    await event.deleteMany({});
    for(let i=0;i<12;i++){
        const newEvent = new event ({
            EventName : `${eventArray[i].name}`,
            Venue : `${eventArray[i].location}`,
            EventDescription : `${eventArray[i].description}`,
            EventType : `${eventArray[i].type}`,
            Website : `${eventArray[i].website}`,
            Facebook : `${eventArray[i].fb}`,
            Image : `${eventArray[i].image}`,
            TargetAudience : `${eventArray[i].target}`,
            ExpectedFootfall : `${eventArray[i].footfall}`,
            Email : `${eventArray[i].email}`,
            Contact : `${eventArray[i].mobile}`,
        })
        await newEvent.save();
    }
}
console.log(eventArray[1].name)
addEvents().then(()=>{
    mongoose.connection.close();
})